//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReenaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int SDetay_Id { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Siparis_Id { get; set; }
        public Nullable<int> Urun_Id { get; set; }
    
        public virtual Siparisler Siparisler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
